### ISSUE TITLE
Hi Paul. react-spotify questions. Many thanks in advance

### ISSUE THREAD

**Issue by maxsilvauk** [Pau1fitz/react-spotify#20]
I am writing my own Spotify player app and have seen quite a few online and am interested how are you getting access to peoples data yet I haven't granted your application access to my data following the link:- http://pau1fitz.github.io/react-spotify. It just asks me to sign into Spotify but I do not get the popup to grant you access that I see in other examples. 

Also another question is are you using expressJS  to get the bearer token I can only see the react front-end?

I cant seem to run the project locally but thats not a problem just trying to make sure I am going down the right path.

**Comment by Pau1fitz** [comment]
Hi @maxsilvauk 

It is a while since I set this up, but all the permissions are set out [here](https://github.com/Pau1fitz/react-spotify/blob/master/src/App.js#L36).

If there is no access token it will redirect you to this and request to be allowed access to all the different user data. I am not sure why you aren't explicitly being asked this.

There are a few ways to get access tokens. One way is to set up a node server, but this just does it all in the browser, no server side code required.

What error are you seeing when you try and run the project locally?

**Comment by maxsilvauk** [comment]
Hi @Pau1fitz. Thank for the quick response. Ha now I've looked it at more properly I can see you are sending users using the window.href interesting. Yeh its really weird your app does not appear in my apps list that I have allowed access to my data yet I login and your able to use my data strange:- attached a screenshot of this. 

<img width="1920" alt="Screenshot 2020-06-13 at 16 48 08" src="https://user-images.githubusercontent.com/580488/84573008-dbf1a300-ad95-11ea-8d2c-b63d233a433a.png">


I guess doing it the express way hides all the sensitive data from the browser. I may go down that route. 

This is the error I am seeing when running your code locally. Please see screenshot

<img width="1920" alt="Screenshot 2020-06-13 at 16 50 01" src="https://user-images.githubusercontent.com/580488/84573036-faf03500-ad95-11ea-9e7e-a35ad8453527.png">

Thanks again.

**Comment by Pau1fitz** [comment]
Hmm, that's strange. Do you know what version of node you are running? Could you try and update to version 14?

**Comment by Pau1fitz** [comment]
I can see there was a similar issue [here](https://github.com/Pau1fitz/react-spotify/issues/17)

**Comment by maxsilvauk** [comment]
Yes lowering the version of node would make sense. Updating it would still cause an issue. fyi
